### ISSUE TITLE
Bug: mouse::shiftCoords

### ISSUE THREAD

**Issue by RazuvaevDD** [RazuvaevDD/ProjectWork2019Neiro#14]
@AverinLV 
`mouse.shiftCoords(100, 50, 1000);`
in main.cpp goes only to the right
if I write
`mouse.shiftCoords(-100, -1, 1000);`
in main.cpp......... it isn't working.
Check it & Fix this bug pls.

_Originally posted by @RazuvaevDD in https://github.com/RazuvaevDD/ProjectWork2019Neiro/pull/13#issuecomment-473157254_

**Comment by RazuvaevDD** [comment]
@AmRust
When closing the main window, the side windows do not close.

**Comment by AverinLV** [comment]
@RazuvaevDD 
Well, let us look at what you just wrote. It seems like you are a really contused, mentally injured imbecile. I can even say it to you face-to-face, so how about you come here and listen? All this fuckery that you wrote is just complete, utter bullshit, you fucking keyboard warrior. Your life will not get better just because you wrote a lot. Bullshiting is not a hard job, a lot of fags like you thawed out in the spring. People say a lot of things about you. Things like: 'Mom did not want him, dad did not even try'. Keep my message in mind. Try to analyze it and make some conclusions for yourself.

**Comment by AverinLV** [comment]
@RazuvaevDD 
Fixed in 60ffc33. 
[Here you can finally pull changes in master branch](https://github.com/RazuvaevDD/ProjectWork2019Neiro/pull/15)

**Comment by AverinLV** [comment]
Who the fuck are you to delete my comments? Where is fucking freedom of speech you piece of shit?

**Comment by AverinLV** [comment]
Fuck you

**Comment by RazuvaevDD** [comment]
Ok.
