### ISSUE TITLE
Error adding settings to XMLParser

### ISSUE THREAD

**Issue by RazuvaevDD** [RazuvaevDD/ProjectWork2019Neiro#25]
@AverinLV I create a parser, I create a setting, I throw the setting into the parser, and the id1 setting appears in pure XML. Then I create the parser again, create the setting, add it to the analyzer, and in the xml file the first setting is replaced with the new setting, rather than being added next to id1 as id2.

_Originally posted by @RazuvaevDD in https://github.com/RazuvaevDD/ProjectWork2019Neiro/commit/84b6b6d7d073172b88146ca34dd726833c99f43e#commitcomment-32905057_

**Comment by AverinLV** [comment]
@AmRust 
I'm smoking and I don't give a fuck
I'm drinking and I don't give a fuck
I'm eating pills and I don't give a fuck
I've fucked a bitch without condom and I don't give a fuck
20 thousands on a sneakers I'm wasting money on a shit and wasting it without stop.

**Comment by AverinLV** [comment]
пеши по руски я по американски не понимаю

**Comment by AverinLV** [comment]
хуйлуша

**Comment by AverinLV** [comment]
пошел ты нахуй

**Comment by AverinLV** [comment]
еще будешь мои комменты удалять

**Comment by AverinLV** [comment]
гнойный червь

**Comment by AverinLV** [comment]
хуй соси быдло

**Comment by AverinLV** [comment]
@RazuvaevDD  пошел наахууууууууууй

**Comment by AverinLV** [comment]
@RazuvaevDD 
You should run loadXML function after creating parser. It's not good idea to place loadXML in constructor because if loadXML running from constructor it can't find file because XMLParser.cpp is placed in Settings folder and there is no Settings.xml file. 
If loadXML running from constructor it search Settings.xml in Settings folder
if loadXML running from main.cpp it search Settings.xml in folder with main.cpp. To avoid any incidents with file location it'll much more safer to make loadXML public and run it after constructor.
Fixed in 1af5537

**Comment by RazuvaevDD** [comment]
@AverinLV If loadXML is started from constructor, it looks for the Settings file.xml in the settings folder .
If loadXML is running from main.cpp, it looks for the Settings file.xml in the main folder
If loadXML is running from the gui.cpp or other files, it is bound to the location of the given file.
Isn't it easier to just store settings in a settings folder so you can access settings from any cpp file?

**Comment by AverinLV** [comment]
@RazuvaevDD 
If you want to use XMLParser from another cpp file you just need to write path to Settings.xml from cpp file where you using it in constructor. For example, if you want to run it from gui.cpp you should run constructor this way:
`Settings_module::XMLParser p("../Settings/Settings.xml");`
And everything will be ok

**Comment by RazuvaevDD** [comment]
Ok
